In [144]:
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk import pos_tag
from sklearn.preprocessing import LabelEncoder
from sklearn.base import BaseEstimator, TransformerMixin
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn import set_config
set_config(display="diagram")
from sklearn.naive_bayes import ComplementNB
from sklearn.metrics import classification_report
from sklearn.metrics import plot_roc_curve, roc_auc_score,plot_confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import plot_roc_curve, auc,roc_curve,roc_auc_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR
import xgboost as xgb

In [106]:
df = pd.read_csv('/Users/mahmoud/Car_Price_Prediction/merged_official_data.csv')

In [107]:
df = df.drop(columns=['Unnamed: 0'])
df

,Car Name,Car Rating,Reviews,Year,Mileage,Dealer Name,Dealer Rating,Review Count,Price
0,2013 Nissan Xterra PRO-4X,4.5,"['March 15, 2021\nBy Tony from Detroit\nOwns t...",2013,163000.0,Priced Right Auto,0.0,19.0,9500.0
1,2014 Hyundai Elantra SE,4.5,"['May 7, 2022\nBy Talessa from Tulsa, ok\nOwn...",2014,95747.0,Blasius Pre-Owned Auto,4.4,75.0,8994.0
2,2014 Hyundai Elantra SE,4.5,"['May 7, 2022\nBy Talessa from Tulsa, ok\nOwn...",2014,159177.0,Metro Motors LLC,0.0,1.0,8900.0
3,2014 Hyundai Elantra SE,4.5,"['May 7, 2022\nBy Talessa from Tulsa, ok\nOwn...",2014,79055.0,Oakbrook Toyota in Westmont,4.5,2527.0,10304.0
4,2014 Hyundai Elantra SE,4.5,"['May 7, 2022\nBy Talessa from Tulsa, ok\nOwn...",2014,102894.0,Sawari Automotive Group,4.7,31.0,9599.0
...,...,...,...,...,...,...,...,...,...
13691,2005 Dodge Ram 1500 SLT/Laramie Quad Cab,5.0,"['May 8, 2023\nBy Michael from Nashville \nO...",2005,171430.0,Broadway Auto Mall,0.0,16.0,5980.0
13692,2005 Dodge Ram 1500 SLT/Laramie Quad Cab,5.0,"['May 8, 2023\nBy Michael from Nashville \nO...",2005,153560.0,Trucks Plus Idaho,0.0,2.0,9988.0
13693,2014 Audi A4 Premium Plus,4.4,"['September 7, 2022\nBy SInce59 from Napa, Ca...",2014,138173.0,Your Choice Auto Sales of Elgin,4.4,57.0,12999.0
13694,2011 BMW 535 xDrive,4.5,"['June 2, 2022\nBy Manuel from Liberal Ks\nOw...",2011,146541.0,Best Choice Auto Sales,0.0,37.0,9990.0
13695,2011 BMW 535 xDrive,4.5,"['June 2, 2022\nBy Manuel from Liberal Ks\nOw...",2011,103001.0,MC Auto Mart LLC,0.0,0.0,13999.0

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13696 entries, 0 to 13695
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car Name       13696 non-null  object
 1   Car Rating     13696 non-null  float64
 2   Reviews        13696 non-null  object
 3   Year           13696 non-null  int64
 4   Mileage        13696 non-null  float64
 5   Dealer Name    13696 non-null  object
 6   Dealer Rating  13696 non-null  float64
 7   Review Count   13696 non-null  float64
 8   Price          13696 non-null  float64
dtypes: float64(5), int64(1), object(3)
memory usage: 963.1+ KB

In [109]:
encoded_df = pd.get_dummies(df, columns=['Car Name', 'Dealer Name'])

# Display the first few rows of the encoded DataFrame
encoded_df

,Car Rating,Reviews,Year,Mileage,Dealer Rating,Review Count,Price,Car Name_1967 Ford Thunderbird Neiman Marcus,Car Name_1972 Buick Skylark Custom,Car Name_1972 Lincoln Continental Mark IV,...,Dealer Name_Zimmerman Honda,Dealer Name_Zoellner Ford Lincoln Beatrice,Dealer Name_Zone Motors,Dealer Name_Zoom Auto,Dealer Name_carneed,Dealer Name_iCars Chicago,Dealer Name_iDrive Auto Group,Dealer Name_iGOTCARS,Dealer Name_iMotors,Dealer Name_xDrive Motors Inc.
0,4.5,"['March 15, 2021\nBy Tony from Detroit\nOwns t...",2013,163000.0,0.0,19.0,9500.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,4.5,"['May 7, 2022\nBy Talessa from Tulsa, ok\nOwn...",2014,95747.0,4.4,75.0,8994.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,4.5,"['May 7, 2022\nBy Talessa from Tulsa, ok\nOwn...",2014,159177.0,0.0,1.0,8900.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4.5,"['May 7, 2022\nBy Talessa from Tulsa, ok\nOwn...",2014,79055.0,4.5,2527.0,10304.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4.5,"['May 7, 2022\nBy Talessa from Tulsa, ok\nOwn...",2014,102894.0,4.7,31.0,9599.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13691,5.0,"['May 8, 2023\nBy Michael from Nashville \nO...",2005,171430.0,0.0,16.0,5980.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13692,5.0,"['May 8, 2023\nBy Michael from Nashville \nO...",2005,153560.0,0.0,2.0,9988.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13693,4.4,"['September 7, 2022\nBy SInce59 from Napa, Ca...",2014,138173.0,4.4,57.0,12999.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13694,4.5,"['June 2, 2022\nBy Manuel from Liberal Ks\nOw...",2011,146541.0,0.0,37.0,9990.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13695,4.5,"['June 2, 2022\nBy Manuel from Liberal Ks\nOw...",2011,103001.0,0.0,0.0,13999.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [110]:
class TextPreprocessor(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.wnl = WordNetLemmatizer()
        self.stop_words = set(stopwords.words('english'))

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X_norm = X.apply(self.process_doc)
        return X_norm

    def process_doc(self, doc):
        def pos_tagger(nltk_tag):
            if nltk_tag.startswith('J'):
                return wordnet.ADJ
            elif nltk_tag.startswith('V'):
                return wordnet.VERB
            elif nltk_tag.startswith('N'):
                return wordnet.NOUN
            elif nltk_tag.startswith('R'):
                return wordnet.ADV
            else:
                return None
            
        # remove stop words and punctuations, then lower case
        doc_norm = [tok.lower() for tok in word_tokenize(doc) if tok.isalpha() and tok.lower() not in self.stop_words]
        
        #  POS detection on the result will be important in telling Wordnet's lemmatizer how to lemmatize
        
        # creates list of tuples with tokens and POS tags in wordnet format
        wordnet_tagged = list(map(lambda x: (x[0], pos_tagger(x[1])), pos_tag(doc_norm)))
        doc_norm = [self.wnl.lemmatize(token, pos) for token, pos in wordnet_tagged if pos is not None]
        return " ".join(doc_norm)

In [50]:
nltk.download('vader_lexicon')
sentiment_analyzer = SentimentIntensityAnalyzer()
# it only goes from -1 to +1
def get_sentiment(review):
    sentiment_score = sentiment_analyzer.polarity_scores(review)
    if sentiment_score['compound'] > 0:
        return 'Positive'
    elif sentiment_score['compound'] < 0:
        return 'Negative'
    else:
        return 'Neutral'

encoded_df['Sentiment'] = encoded_df['Reviews'].apply(get_sentiment)

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/mahmoud/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [51]:
encoded_df

,Car Rating,Reviews,Year,Mileage,Dealer Rating,Review Count,Price,Car Name_1967 Ford Thunderbird Neiman Marcus,Car Name_1972 Buick Skylark Custom,Car Name_1972 Lincoln Continental Mark IV,...,Dealer Name_Zoellner Ford Lincoln Beatrice,Dealer Name_Zone Motors,Dealer Name_Zoom Auto,Dealer Name_carneed,Dealer Name_iCars Chicago,Dealer Name_iDrive Auto Group,Dealer Name_iGOTCARS,Dealer Name_iMotors,Dealer Name_xDrive Motors Inc.,Sentiment
0,4.5,"['March 15, 2021\nBy Tony from Detroit\nOwns t...",2013,163000.0,0.0,19.0,9500.0,0,0,0,...,0,0,0,0,0,0,0,0,0,Positive
1,4.5,"['May 7, 2022\nBy Talessa from Tulsa, ok\nOwn...",2014,95747.0,4.4,75.0,8994.0,0,0,0,...,0,0,0,0,0,0,0,0,0,Negative
2,4.5,"['May 7, 2022\nBy Talessa from Tulsa, ok\nOwn...",2014,159177.0,0.0,1.0,8900.0,0,0,0,...,0,0,0,0,0,0,0,0,0,Negative
3,4.5,"['May 7, 2022\nBy Talessa from Tulsa, ok\nOwn...",2014,79055.0,4.5,2527.0,10304.0,0,0,0,...,0,0,0,0,0,0,0,0,0,Negative
4,4.5,"['May 7, 2022\nBy Talessa from Tulsa, ok\nOwn...",2014,102894.0,4.7,31.0,9599.0,0,0,0,...,0,0,0,0,0,0,0,0,0,Negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13691,5.0,"['May 8, 2023\nBy Michael from Nashville \nO...",2005,171430.0,0.0,16.0,5980.0,0,0,0,...,0,0,0,0,0,0,0,0,0,Positive
13692,5.0,"['May 8, 2023\nBy Michael from Nashville \nO...",2005,153560.0,0.0,2.0,9988.0,0,0,0,...,0,0,0,0,0,0,0,0,0,Positive
13693,4.4,"['September 7, 2022\nBy SInce59 from Napa, Ca...",2014,138173.0,4.4,57.0,12999.0,0,0,0,...,0,0,0,0,0,0,0,0,0,Positive
13694,4.5,"['June 2, 2022\nBy Manuel from Liberal Ks\nOw...",2011,146541.0,0.0,37.0,9990.0,0,0,0,...,0,0,0,0,0,0,0,0,0,Positive
13695,4.5,"['June 2, 2022\nBy Manuel from Liberal Ks\nOw...",2011,103001.0,0.0,0.0,13999.0,0,0,0,...,0,0,0,0,0,0,0,0,0,Positive

# Making sure model works by using just Processed_Reviews

In [124]:
X = df['Processed_Reviews']
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

RMSE: 2163.2402436268876

In [ ]:
text_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),   # Using TF-IDF vectorizer for text representation
    ('model', LinearRegression())   # Linear Regression model
])

In [ ]:
text_pipeline.fit(X_train, y_train)

In [ ]:
y_pred = text_pipeline.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print("RMSE:", rmse)

# Random Forest

In [129]:
X = df.drop(['Price'], axis=1)
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [130]:
text_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),   
])

numerical_pipeline = Pipeline([
    ('scaler', StandardScaler()),  
])

In [131]:
preprocessor = ColumnTransformer([
    ('text', text_pipeline, 'Processed_Reviews'),    
    ('numerical', numerical_pipeline, ['Car Rating', 'Year', 'Mileage', 'Dealer Rating', 'Review Count']), 
])

In [132]:
model = Pipeline([
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(random_state=42)) 
])
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print("R_Squared:", r2)
print("Root Mean Squared Error:", rmse)

R_Squared: 0.7923216716471226
Root Mean Squared Error: 1184.8805139606172

# Gradient Boost

In [134]:
X = df.drop(['Price'], axis=1)
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [135]:
text_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),   
])

numerical_pipeline = Pipeline([
    ('scaler', StandardScaler()),  
])

In [136]:
preprocessor = ColumnTransformer([
    ('text', text_pipeline, 'Processed_Reviews'),    
    ('numerical', numerical_pipeline, ['Car Rating', 'Year', 'Mileage', 'Dealer Rating', 'Review Count']), 
])

In [137]:
model = Pipeline([
    ('preprocessor', preprocessor),
    ('model', GradientBoostingRegressor(random_state=42))   
])
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print("R_Squared:", r2)
print("Root Mean Squared Error:", rmse)

R_Squared: 0.48476364515977877
Root Mean Squared Error: 1866.303270577574

# XGBoost

In [177]:
X = df.drop(['Price'], axis=1)
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [178]:
text_pipeline = Pipeline([
    ('tfidf', TfidfVectorizer()),   
])

numerical_pipeline = Pipeline([
    ('scaler', StandardScaler()),  
])

In [179]:
preprocessor = ColumnTransformer([
    ('text', text_pipeline, 'Processed_Reviews'),    
    ('numerical', numerical_pipeline, ['Car Rating', 'Year', 'Mileage', 'Dealer Rating', 'Review Count']), 
])

In [180]:
model = xgb.XGBRegressor()
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('model', model),
])

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print("R_Squared:", r2)
print("Root Mean Squared Error:", rmse)

R_Squared: 0.6719201648596869
Root Mean Squared Error: 1489.2538675886217

# Neural Network

In [181]:
X = df.drop('Price', axis=1)
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [182]:
numeric_features = ['Car Rating', 'Year', 'Mileage', 'Dealer Rating', 'Review Count']

numeric_pipeline = Pipeline([
    ('scaler', StandardScaler())
])

X_train_scaled = numeric_pipeline.fit_transform(X_train[numeric_features])
X_test_scaled = numeric_pipeline.transform(X_test[numeric_features])

In [183]:
pipeline_nn = Pipeline([
    ('regressor', MLPRegressor(hidden_layer_sizes=(100, 50), random_state=42, max_iter=500))
])

pipeline_nn.fit(X_train_scaled, y_train)

y_pred_nn = pipeline_nn.predict(X_test_scaled)

rmse_nn = mean_squared_error(y_test, y_pred_nn, squared=False)
r2 = r2_score(y_test, y_pred)
print("R_Squared:", r2)
print("Neural Network RMSE:", rmse_nn)

R_Squared: 0.6719201648596869
Neural Network RMSE: 2228.8358324177734

# KNN

In [184]:
X = df.drop('Price', axis=1)
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [185]:
numeric_features = ['Car Rating', 'Year', 'Mileage', 'Dealer Rating', 'Review Count']

numeric_pipeline = Pipeline([
    ('scaler', StandardScaler())
])

X_train_scaled = numeric_pipeline.fit_transform(X_train[numeric_features])
X_test_scaled = numeric_pipeline.transform(X_test[numeric_features])

In [186]:
pipeline_knn = Pipeline([
    ('regressor', KNeighborsRegressor(n_neighbors=5))
])
pipeline_knn.fit(X_train_scaled, y_train)

y_pred_knn = pipeline_knn.predict(X_test_scaled)

rmse_knn = mean_squared_error(y_test, y_pred_knn, squared=False)
r2 = r2_score(y_test, y_pred)
print("R_Squared:", r2)
print("KNN RMSE:", rmse_knn)

R_Squared: 0.6719201648596869
KNN RMSE: 2301.956363798436

- so best model is Random Forest. Lets tune it

In [189]:
X = df.drop('Price', axis=1)
y = df['Price']

numeric_features = ['Car Rating', 'Year', 'Mileage', 'Dealer Rating', 'Review Count']
categorical_features = ['Car Name', 'Reviews', 'Dealer Name', 'Processed_Reviews']

numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

rf = RandomForestRegressor(random_state=42)

pipeline_rf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', rf)
])

rf_params = {
    'regressor__n_estimators': [100, 200, 300],
    'regressor__max_depth': [None, 10, 20, 30],
    'regressor__min_samples_split': [2, 5, 10],
    'regressor__min_samples_leaf': [1, 2, 4]
}

rf_random_search = RandomizedSearchCV(pipeline_rf, param_distributions=rf_params, n_iter=10, scoring='neg_root_mean_squared_error', cv=5, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

rf_random_search.fit(X_train, y_train)

best_rf = rf_random_search.best_estimator_

y_pred_rf = best_rf.predict(X_test)

rmse_rf = mean_squared_error(y_test, y_pred_rf, squared=False)
r2 = r2_score(y_test, y_pred_rf)
print("R_Squared:", r2)
print("Random Forest Regressor RMSE:", rmse_rf)

R_Squared: 0.729889480445979
Random Forest Regressor RMSE: 1351.2935903078742

In [196]:
X = df.drop('Price', axis=1)
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [197]:
numeric_features = ['Car Rating', 'Year', 'Mileage', 'Dealer Rating', 'Review Count']
categorical_features = ['Car Name', 'Reviews', 'Dealer Name', 'Processed_Reviews']

numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])
preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

In [198]:
rf = RandomForestRegressor(random_state=42)

pipeline_rf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', rf)
])

rf_params = {
    'regressor__n_estimators': [100, 200, 300],
    'regressor__max_depth': [None, 10, 20, 30],
    'regressor__min_samples_split': [2, 5, 10],
    'regressor__min_samples_leaf': [1, 2, 4]
}
rf_random_search = RandomizedSearchCV(pipeline_rf, param_distributions=rf_params, n_iter=10, 
                                      scoring='neg_root_mean_squared_error', cv=5, random_state=42)

best_rf = rf_random_search.best_estimator_

y_pred_rf = best_rf.predict(X_test)

rmse_rf = mean_squared_error(y_test, y_pred_rf, squared=False)
r2 = r2_score(y_test, y_pred_rf)
print("R_Squared:", r2)
print("Random Forest Regressor RMSE:", rmse_rf)

AttributeError: 'RandomizedSearchCV' object has no attribute 'best_estimator_'

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('text', TfidfVectorizer(), 'Processed_Reviews'),
        ('num', 'passthrough', ['Car Rating', 'Year', 'Mileage', 'Dealer Rating', 'Review Count'])
    ])

rf = RandomForestRegressor(random_state=42)

pipeline_rf = Pipeline(steps=[('preprocessor', preprocessor),
                               ('rf', rf)])

param_grid = {
    'rf__n_estimators': [100, 200, 300],
    'rf__max_depth': [None, 10, 20],
    'rf__min_samples_split': [2, 5, 10],
    'rf__min_samples_leaf': [1, 2, 4],
    'rf__bootstrap': [True, False]
}
grid_search = GridSearchCV(estimator=pipeline_rf, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)

grid_search.fit(X_train, y_train)

best_params = grid_search.best_params_
best_rf_model = grid_search.best_estimator_

y_pred = best_rf_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r_squared = best_rf_model.score(X_test, y_test)

print("Best Hyperparameters:", best_params)
print("Random Forest Regressor RMSE:", rmse)
print("R-squared:", r_squared)

In [202]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error
import numpy as np

# Step 1: Define the column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('text', TfidfVectorizer(), 'Processed_Reviews'),
        ('num', 'passthrough', ['Car Rating', 'Year', 'Mileage', 'Dealer Rating', 'Review Count'])
    ])

# Step 2: Create the Random Forest Regressor model
rf = RandomForestRegressor(random_state=42)

# Step 3: Create the pipeline
pipeline_rf = Pipeline(steps=[('preprocessor', preprocessor),
                               ('rf', rf)])

# Step 4: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 5: Define the parameter grid to search
param_grid = {
    'rf__n_estimators': [100, 200, 300],
    'rf__max_depth': [None, 10, 20],
    'rf__min_samples_split': [2, 5, 10],
    'rf__min_samples_leaf': [1, 2, 4],
    'rf__bootstrap': [True, False]
}

# Step 6: Create the GridSearchCV object
grid_search = GridSearchCV(estimator=pipeline_rf, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)

# Step 7: Fit the GridSearchCV to the data
grid_search.fit(X_train, y_train)

# Step 8: Get the best hyperparameters and the best model
best_params = grid_search.best_params_
best_rf_model = grid_search.best_estimator_

# Step 9: Evaluate the best model on the test set
y_pred = best_rf_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r_squared = best_rf_model.score(X_test, y_test)

print("Best Hyperparameters:", best_params)
print("Random Forest Regressor RMSE:", rmse)
print("R-squared:", r_squared)

Fitting 5 folds for each of 162 candidates, totalling 810 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed: 27.7min
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed: 129.3min
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed: 217.5min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed: 447.7min
[Parallel(n_jobs=-1)]: Done 810 out of 810 | elapsed: 582.0min finished

Best Hyperparameters: {'rf__bootstrap': True, 'rf__max_depth': None, 'rf__min_samples_leaf': 1, 'rf__min_samples_split': 2, 'rf__n_estimators': 300}
Random Forest Regressor RMSE: 1181.995214290282
R-squared: 0.7933318741658443

# Gradient Boost tuned

In [190]:
X = df.drop('Price', axis=1)
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [191]:
numeric_features = ['Car Rating', 'Year', 'Mileage', 'Dealer Rating', 'Review Count']
categorical_features = ['Car Name', 'Reviews', 'Dealer Name', 'Processed_Reviews']

# Create preprocessor for numeric features
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

# Create preprocessor for categorical features
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Combine numeric and categorical transformers using ColumnTransformer
preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, numeric_features),
    ('cat', categorical_transformer, categorical_features)
])

In [192]:
xgb = XGBRegressor(random_state=42)

# Create the pipeline
pipeline_xgb = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', xgb)
])

# XGBoost hyperparameters to tune
xgb_params = {
    'regressor__n_estimators': [100, 200, 300],
    'regressor__learning_rate': [0.05, 0.1, 0.2],
    'regressor__max_depth': [3, 5, 7],
    'regressor__subsample': [0.8, 0.9, 1.0],
    'regressor__colsample_bytree': [0.8, 0.9, 1.0],
    'regressor__gamma': [0, 0.1, 0.2],
    'regressor__min_child_weight': [1, 2, 3]
}
xgb_random_search = RandomizedSearchCV(pipeline_xgb, param_distributions=xgb_params, n_iter=10, scoring='neg_root_mean_squared_error', cv=5, random_state=42)
xgb_random_search.fit(X_train, y_train)
best_xgb = xgb_random_search.best_estimator_
y_pred_xgb = best_xgb.predict(X_test)
rmse_xgb = mean_squared_error(y_test, y_pred_xgb, squared=False)
r2_xgb = r2_score(y_test, y_pred_xgb)
print("R_Squared:", r2_xgb)
print("XGBoost Regressor RMSE:", rmse_xgb)

R_Squared: 0.631847634920814
XGBoost Regressor RMSE: 1577.5849882281725